[package]
name = "advent"
version = "0.1.0"
edition = "2021"
default-run = "advent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
anyhow = "1.0"
reflect = "0.0.13"